### ISSUE TITLE
Error for FortSDKv1.6

### ISSUE THREAD

**Issue by riocallos** [payfort/fort-android-sdk#16]
Experience a crash when 
            minifyEnabled true
            shrinkResources true

` java.lang.IllegalAccessError: Field 'org.apache.commons.codec.binary.Base64.CHUNK_SEPARATOR' is inaccessible to class 'com.payfort.sdk.android.dependancies.security.aes.AESCipher' (declaration of 'com.payfort.sdk.android.dependancies.security.aes.AESCipher' appears in base.apk!classes2.dex)
        at com.payfort.sdk.android.dependancies.security.aes.AESCipher.getDecryptedMessage(AESCipher.java:7)
        at com.payfort.sdk.android.dependancies.security.aes.AESCipherManager.decryptMsg(AESCipherManager.java:2)
        at com.payfort.fort.android.sdk.activities.InitSecureConnectionActivity$Handshake.onPostExecute(InitSecureConnectionActivity.java:3)
        at com.payfort.fort.android.sdk.activities.InitSecureConnectionActivity$Handshake.onPostExecute(InitSecureConnectionActivity.java:1)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.access$600(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

this is how my proguard-rules.pro looks

`-keep class othercode.** { *; }
-dontwarn com.payfort.**
-keep class com.payfort.** { *; }
-keep public interface com.payfort.** {*;}
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.content.BroadcastReceiver
-keep class javax.** { *; }
-dontwarn de.keyboardsurfer.**
-keep class de.keyboardsurfer.** { *; }
-dontwarn com.google.**
-keep class com.google.** { *; }
-dontwarn org.bouncycastle.**
-keep class org.bouncycastle.** { *; }
-dontwarn commons-codec.**
-keep class commons-codec.** { *; }
-dontwarn com.victor.**
-keep class com.victor.** { *; }
-dontwarn com.shamanland.**
-keep class com.shamanland.** { *; }
-dontwarn com.android.**
-keep class com.android.** { *; }

-dontwarn androidx.**
-keep class androidx.** { *; }
-keep interface androidx.** { *; }

-dontwarn com.google.android.material.textfield.**
-keep com.google.android.material.textfield.** { *; }
-keep com.google.android.material.textfield.** { *; }`

**Comment by PayFortIntegration** [comment]
Hi Riocallos,

Can you please check and make sure you are including all our Proguard rules included in our SDK file?
Below our Proguard must be added in the application.

if that did not solve the problem, please share the proguard added in your application.

for any further assistance, please contact us directly on "integration@payfort.com"


========================
`# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in C:\Users\gbarham\AppData\Local\Android\sdk/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

-keep class othercode.** { *; }
-dontwarn com.payfort.**
-keep class com.payfort.** { *; }
-keep public interface com.payfort.** {*;}
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.content.BroadcastReceiver
-keep class javax.** { *; }
-dontwarn de.keyboardsurfer.**
-keep class de.keyboardsurfer.** { *; }
-dontwarn com.google.**
-keep class com.google.** { *; }
-dontwarn org.bouncycastle.**
-keep class org.bouncycastle.** { *; }
-dontwarn commons-codec.**
-keep class commons-codec.** { *; }
-dontwarn com.victor.**
-keep class com.victor.** { *; }
-dontwarn com.shamanland.**
-keep class com.shamanland.** { *; }
-dontwarn com.android.**
-keep class com.android.** { *; }

-dontwarn androidx.**
-keep class androidx.** { *; }
-keep interface androidx.** { *; }

-dontwarn com.google.android.material.textfield.**
-keep com.google.android.material.textfield.** { *; }
-keep com.google.android.material.textfield.** { *; }
`
========================

**Comment by riocallos** [comment]
Hello,

Actually the progaurd.txt you attached produces a compile error in Android studio for the last three lines.
`Expected [!]interface|@interface|class|enum`

I can confirm that I have the same proguard as the one you've sent (after fixing the error). I'm attaching it here. Still the same crash.

[proguard-rules.txt](https://github.com/payfort/fort-android-sdk/files/4923448/proguard-rules.txt)

**Comment by PayFortIntegration** [comment]
Hi Riocallos,


Thanks for your reply, can you please try the attached file, and confirm normal operations. 


[proguard-rules.txt](https://github.com/payfort/fort-android-sdk/files/4924863/proguard-rules.txt)

**Comment by riocallos** [comment]
Hello,

Applied the new proguard you attached. Still the same crash/error.

`java.lang.IllegalAccessError: Field 'org.apache.commons.codec.binary.Base64.CHUNK_SEPARATOR' is inaccessible to class 'com.payfort.sdk.android.dependancies.security.aes.AESCipher' (declaration of 'com.payfort.sdk.android.dependancies.security.aes.AESCipher' appears in base.apk!classes2.dex)`
