### ISSUE TITLE
java.lang.NoClassDefFoundError: BaseEncoding

### ISSUE THREAD

**Issue by amorenew** [payfort/fort-android-sdk#3]
I got this crash
`  java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                      at android.os.AsyncTask$3.done(AsyncTask.java:353)
                                                                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                                                      at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                      at java.lang.Thread.run(Thread.java:764)
                                                                   Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/io/BaseEncoding;
                                                                      at com.payfort.sdk.android.dependancies.security.aes.AESCipher.getEncryptedMessage(AESCipher.java:87)
                                                                      at com.payfort.sdk.android.dependancies.security.aes.AESCipherManager.encryptData(AESCipherManager.java:24)
                                                                      at com.payfort.sdk.android.dependancies.security.DataSecurityService.encryptRequestData(DataSecurityService.java:54)
                                                                      at com.payfort.fort.android.sdk.activities.InitSecureConnectionActivity$Handshake.doInBackground(InitSecureConnectionActivity.java:128)
                                                                      at com.payfort.fort.android.sdk.activities.InitSecureConnectionActivity$Handshake.doInBackground(InitSecureConnectionActivity.java:95)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                      at java.lang.Thread.run(Thread.java:764) 
                                                                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.common.io.BaseEncoding" on path: DexPathList[[zip file "/data/app/co.fursan.ejazah-6_JJQ4YTJZl1EgxQ7H_Zeg==/base.apk"],nativeLibraryDirectories=[/data/app/co.fursan.ejazah-6_JJQ4YTJZl1EgxQ7H_Zeg==/lib/x86, /data/app/co.fursan.ejazah-6_JJQ4YTJZl1EgxQ7H_Zeg==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
                                                                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                      at com.payfort.sdk.android.dependancies.security.aes.AESCipher.getEncryptedMessage(AESCipher.java:87) 
                                                                      at com.payfort.sdk.android.dependancies.security.aes.AESCipherManager.encryptData(AESCipherManager.java:24) 
                                                                      at com.payfort.sdk.android.dependancies.security.DataSecurityService.encryptRequestData(DataSecurityService.java:54) 
                                                                      at com.payfort.fort.android.sdk.activities.InitSecureConnectionActivity$Handshake.doInBackground(InitSecureConnectionActivity.java:128) 
                                                                      at com.payfort.fort.android.sdk.activities.InitSecureConnectionActivity$Handshake.doInBackground(InitSecureConnectionActivity.java:95) 
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:333) 
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                      at java.lang.Thread.run(Thread.java:764) `

**Comment by amorenew** [comment]
the bug in package com.payfort.sdk.android.dependancies.security.aes;
class AESCipher

method

    ```
public String getEncryptedMessage(String message) {
        try {
            Cipher cipher = this.getCipher(1);
            byte[] encryptedTextBytes = cipher.doFinal(message.getBytes("UTF-8"));
            return BaseEncoding.base64().encode(encryptedTextBytes);
        } catch (Exception var4) {
            throw Throwables.propagate(var4);
        }
    }

```

**Comment by mohannadsaleh** [comment]
Hello, 

Thanks for contacting us , can you please contact our integration team at integration@payfort.com , they will assist/provide you with the list of dependencies for the fort android sdk to be integrated also will follow up and help during the integration process .

Best Regards, 
Mohannad Saleh

**Comment by amorenew** [comment]
solution 
I decompiled the library and add it as a module
https://github.com/amorenew/payfort

**Comment by zahid--ali** [comment]
@amorenew @mohannadsaleh  
I just faced this issue. Is there any update or release where this issue is fixed. 
I am facing this in Production Environment. In Test Environment it's working perfectly.
I followed each and every step of the documentation.

**Comment by amreniouinnovent** [comment]
@zahid--ali what I used already add a module instead if jar or aar
https://github.com/amorenew/payfort

**Comment by PayFortIntegration** [comment]
Hi @zahid--ali ,

Can you please email us on integration@payfort.com and share with us the issue you experience ? 
you may need to provide us in the ticket more logs .

Thanks.

**Comment by zahid--ali** [comment]
@PayFortIntegration 
![Screen Shot 2019-08-20 at 12 06 24 PM](https://user-images.githubusercontent.com/6501619/63344733-c9673280-c359-11e9-8eb1-a086a303365e.png)
Please find the Logcat crash log in the above image

**Comment by PayFortIntegration** [comment]
Hi @zahid--ali 
Please send this image in email to our email address (integration@payfort.com) in order to assist you properly.

**Comment by zahid--ali** [comment]
The issue seems in ProGuard  rules. Please guide me how to add the payfort ProGuard rules in my application code.

**Comment by zahid--ali** [comment]
@amorenew  can you explain here what is the bug in the code?

**Comment by amreniouinnovent** [comment]
@zahid--ali I don't remember it was a long time ago but by extracting the jar file and making the project manually I was able to success

**Comment by zahid--ali** [comment]
The issue seems in ProGaurd rules. Either I am not getting it or the document is no clear. @PayFortIntegration

**Comment by PayFortIntegration** [comment]
Hi @zahid--ali 
Please send your query in email to (integration@payfort.com) this is in order to answer and assist you propelry. 

Thank you.

**Comment by Widuka** [comment]
@zahid--ali tell me if you have "-dontobfuscate" rule in your proguard-rules file? In my project its make crash. When I delete it everything starts work fine.  I don't understand this logic, but it works.

**Comment by riocallos** [comment]
What is the resolution for this? I am having the same problem.

**Comment by shahzadafridi** [comment]
If someone is still having an issue with payfort while enabling pro guard rules here is the rules which works for me.

```
# Payfort SDK
-dontwarn com.payfort.**
-keep class com.payfort.** { *; }
-keep public interface com.payfort.** {*;}
```

**Comment by Ma7moud3ly** [comment]
> If someone is still having an issue with payfort while enabling pro guard rules here is the rules which works for me.
> 
> ```
> # Payfort SDK
> -dontwarn com.payfort.**
> -keep class com.payfort.** { *; }
> -keep public interface com.payfort.** {*;}
> ```

Thanks a lot that's worked with me

**Comment by mays123** [comment]
> If someone is still having an issue with payfort while enabling pro guard rules here is the rules which works for me.
> 
> ```
> # Payfort SDK
> -dontwarn com.payfort.**
> -keep class com.payfort.** { *; }
> -keep public interface com.payfort.** {*;}
> ```

Thank you very much, it should be added to the documentation @PayFortIntegration
